# Generated by Django 5.0.6 on 2024-06-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('edited_date', models.DateField(auto_now=True)),
                ('dead_line', models.DateField(null=True)),
                ('requirements', models.TextField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('experience_min', models.IntegerField()),
                ('experience_max', models.IntegerField()),
                ('work_time', models.CharField(choices=[('Contractual', 'Contractual'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Intern', 'Intern')], default='Full-Time', max_length=20)),
                ('work_type', models.CharField(choices=[('Remote', 'Remote'), ('On-Site', 'On-Site'), ('Hybrid', 'Hybrid')], default='On-Site', max_length=20)),
            ],
        ),
    ]
